### ISSUE TITLE
ModuleNotFoundError: No module named 'modules.encoder.wrn28'

### ISSUE THREAD

**Issue by hqhQAQ** [chenhaoxing/SSFormers#1]
In [https://github.com/chenhaoxing/SSFormers/blob/main/modules/encoder/__init__.py](url), the model `wrn` doesn't exist.

**Comment by chenhaoxing** [comment]
> In [https://github.com/chenhaoxing/SSFormers/blob/main/modules/encoder/**init**.py](url), the model `wrn` doesn't exist.

Sorry for that. I have fixed it.
