### ISSUE TITLE
Ask about visualization code

### ISSUE THREAD

**Issue by WuJi1** [chenhaoxing/SSFormers#8]
Hello author, I read your paper and am very interested in the way you visualize the patch attention in **Figure 5 Visualization of the mask and sparse attention**.  Could you share the visualization method or visualization code if it is convenient?

**Comment by chenhaoxing** [comment]
I’m sorry. This work was done in July, 2021. I can’t find visualization code now. Maybe you can ask the author of paper “DeepEMD” for help.


Best wishes,
Haoxing Chen
Ant Group

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: WuJi1 ***@***.***>
发送时间: Friday, August 4, 2023 3:26:28 PM
收件人: chenhaoxing/SSFormers ***@***.***>
抄送: Subscribed ***@***.***>
主题: [chenhaoxing/SSFormers] Ask about visualization code (Issue #8)


Hello author, I read your paper and am very interested in the way you visualize the patch attention in Figure 5 Visualization of the mask and sparse attention. Could you share the visualization code if it is convenient?

―

**Comment by WuJi1** [comment]
Thank you for your response. That's a shame.
