### ISSUE TITLE
关于Sparse cross attention模块

### ISSUE THREAD

**Issue by whiteany** [chenhaoxing/SSFormers#9]
感谢您的优秀贡献。我尝试找论文中sparse cross attention模块，但是我始终找不到在什么地方。可以麻烦您指出来吗？
![image](https://github.com/chenhaoxing/SSFormers/assets/109933797/3f2ee49d-ce81-4e28-87b5-6deba6000783)

**Comment by chenhaoxing** [comment]
在query/st.py里，80行左右的位置。
```python
q_mask = self._Select_Func(simi_matrix, self.cfg.model.encoder != "FourLayer_64F")  # bxQxNxM_qxM_s 1 40 1 25 1
mask = simi_matrix * q_mask.float().unsqueeze(2).unsqueeze(-1)
```

**Comment by whiteany** [comment]
非常感谢您的回复！
